Repository konveyor/mig-ui, pull requests merged in 2020-06, with the labels that each got.

#879 Add check for existing plan name
  src/app/plan/components/Wizard/WizardContainer.tsx
Labels: needs-ux-design

#899 Add new (incomplete) Tokens page
  src/app/cluster/duck/index.ts
  src/app/common/components/StatusIcon.tsx
  src/app/common/duck/types.ts
  src/app/home/HomeComponent.tsx
  src/app/home/pages/ClustersPage/components/ClustersTable.tsx
  src/app/home/pages/PlansPage/components/Wizard/VolumesForm.tsx
  src/app/home/pages/StoragesPage/components/StoragesTable.tsx
  src/app/home/pages/TokensPage/TokensPage.tsx
  src/app/home/pages/TokensPage/components/TokensTable.tsx
  src/app/home/pages/TokensPage/helpers.ts
  src/app/home/pages/TokensPage/index.ts
  src/app/home/pages/index.ts
  src/app/plan/duck/index.ts
  src/app/plan/duck/types.ts
  src/app/storage/duck/index.ts
  src/app/token/duck/actions.ts
  src/app/token/duck/index.ts
  src/app/token/duck/reducers.ts
  src/app/token/duck/sagas.ts
  src/app/token/duck/selectors.ts
  src/app/token/duck/types.ts
  src/reducers.ts
Labels: non-admin

#903 Add initial loading state
  src/app/cluster/duck/reducers.ts
  src/app/home/pages/ClustersPage/ClustersPage.tsx
  src/app/home/pages/PlansPage/PlansPage.tsx
  src/app/home/pages/StoragesPage/StoragesPage.tsx
  src/app/home/pages/TokensPage/TokensPage.tsx
  src/app/plan/duck/reducers.ts
  src/app/storage/duck/reducers.ts
  src/app/token/duck/reducers.ts
Labels: non-admin

#947 tokenOptions.find only if value not null
  src/app/home/pages/PlansPage/components/Wizard/TokenSelect.tsx
Labels: bug

#900 Welcome screen for non-admin & active namespace select
  src/app/auth/LoginComponent.tsx
  src/app/auth/MockLoginComponent.tsx
  src/app/auth/duck/actions.ts
  src/app/auth/duck/index.ts
  src/app/auth/duck/reducers.ts
  src/app/auth/duck/sagas.ts
  src/app/auth/duck/selectors.ts
  src/app/auth/duck/types.ts
  src/app/cluster/duck/reducers.ts
  src/app/cluster/duck/sagas.ts
  src/app/common/components/ActiveNamespaceModal.tsx
  src/app/common/components/AddEditTokenModal/AddEditTokenModal.tsx
  src/app/common/components/ErrorModal.tsx
  src/app/common/components/PageHeaderComponent.tsx
  src/app/common/components/logoMA.svg
  src/app/common/duck/sagas.ts
  src/app/common/helpers.ts
  src/app/home/HomeComponent.tsx
  src/app/home/pages/ClustersPage/ClustersPage.tsx
  src/app/home/pages/ClustersPage/components/ClustersTable.tsx
  src/app/home/pages/ClustersPage/helpers.ts
  src/app/home/pages/PlansPage/components/Wizard/HooksStep.tsx
  src/app/home/pages/PlansPage/components/Wizard/TokenSelect.tsx
  src/app/home/pages/StoragesPage/StoragesPage.tsx
  src/app/home/pages/WelcomePage/WelcomePage.tsx
  src/app/home/pages/WelcomePage/index.ts
  src/app/home/pages/index.ts
  src/app/plan/duck/sagas.ts
  src/app/plan/duck/selectors.ts
  src/app/storage/duck/sagas.ts
  src/app/token/duck/sagas.ts
  src/client/client_factory.ts
  src/mig_meta.ts
  src/reducers.ts
  src/sagas.ts
Labels: non-admin
