Repository konveyor/mig-ui, pull requests merged in 2020-09, with the labels that each got.

#986 Namespace resources/ migAnalytics support
  src/app/__tests__/AppComponent.test.tsx
  src/app/common/components/namespaces_icon.svg
  src/app/home/pages/PlansPage/PlansPage.tsx
  src/app/home/pages/PlansPage/components/AnalyticsTable.module.scss
  src/app/home/pages/PlansPage/components/AnalyticsTable.tsx
  src/app/home/pages/PlansPage/components/MigrationActions.tsx
  src/app/home/pages/PlansPage/components/MigrationsTable.tsx
  src/app/home/pages/PlansPage/components/PlansTable.module.scss
  src/app/home/pages/PlansPage/components/PlansTable.tsx
  src/app/home/pages/PlansPage/components/VolumesTable.module.scss
  src/app/home/pages/PlansPage/components/Wizard/WizardComponent.tsx
  src/app/home/pages/PlansPage/components/Wizard/WizardContainer.tsx
  src/app/home/pages/PlansPage/helpers.ts
  src/app/plan/duck/actions.ts
  src/app/plan/duck/helpers.ts
  src/app/plan/duck/reducers.ts
  src/app/plan/duck/sagas.ts
  src/app/plan/duck/selectors.ts
  src/app/plan/duck/types.ts
  src/app/plan/duck/utils.ts
  src/client/resources/conversions.ts
  src/client/resources/mig.ts
  src/sagas.ts
Labels: UXD, release-1.3.0

#994 Integrate the DebugTreeView with discovery service
  package.json
  src/__mocks__/store.ts
  src/app/AppComponent.tsx
  src/app/common/components/TreeView/TreeView.tsx
  src/app/common/components/TreeView/TreeViewListItem.tsx
  src/app/debug/components/RawDebugObjectView.tsx
  src/app/debug/duck/actions.ts
  src/app/debug/duck/index.ts
  src/app/debug/duck/reducers.ts
  src/app/debug/duck/sagas.ts
  src/app/debug/duck/types.ts
  src/app/debug/duck/utils.ts
  src/app/home/pages/PlansPage/components/DebugResourcesModal.tsx
  src/app/home/pages/PlansPage/components/PlanActions.tsx
  src/client/resources/discovery.ts
  src/reducers.ts
  src/routes.tsx
  src/sagas.ts
  yarn.lock
Labels: UXD, release-1.3.0

#1016 Add optional chaining to check for empty status in migration selector
  src/app/plan/duck/selectors.ts
Labels: bug, release-1.3.0

#1026 Update title text to MTC branding
  package.json
  public/index.dev.html
  public/index.ejs
  src/app/home/pages/WelcomePage/WelcomePage.tsx
Labels: release-1.3.0
