Repository konveyor/mig-ui, pull requests merged in 2020-04, with the labels that each got.

#808 Convert Storage class table (now Copy options) to PF, add claims and namespaces columns, other UX fixes
  src/app/common/components/FilterToolbar/FilterToolbar.tsx
  src/app/common/components/TableEmptyState.tsx
  src/app/common/duck/hooks.ts
  src/app/common/duck/utils.ts
  src/app/plan/components/Wizard/CopyOptionsForm.tsx
  src/app/plan/components/Wizard/CopyOptionsTable.tsx
  src/app/plan/components/Wizard/NameSpaceTable.tsx
  src/app/plan/components/Wizard/StorageClassForm.tsx
  src/app/plan/components/Wizard/StorageClassTable.tsx
  src/app/plan/components/Wizard/VolumesTable.tsx
  src/app/plan/components/Wizard/WizardComponent.tsx
  src/app/plan/components/Wizard/WizardContainer.tsx
  src/app/plan/components/Wizard/types.ts
  src/client/resources/conversions.ts
Labels: UXD, enhancement

#814 Missing Plan wizard plan name invalid helper
  src/app/common/duck/utils.ts
  src/app/plan/components/Wizard/GeneralForm.tsx
Labels: bug

#840 Plan Wizard: Give focus to plan name
  src/app/plan/components/Wizard/GeneralForm.tsx
Labels: enhancement, look-and-feel
