Repository konveyor/mig-ui, pull requests merged in 2022-06, with the labels that each got.

#1434 Bug 2040695: Fix cluster name validation bug
  src/app/common/duck/utils.ts
  src/app/home/pages/ClustersPage/components/AddEditClusterModal/AddEditClusterForm.tsx
Labels: lgtm

#1438 Bug 2039690: Check for errors and allow promise.all to partially fail for storages
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/AddEditStorageForm.tsx
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/AzureForm.tsx
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/GCPForm.tsx
  src/app/storage/duck/sagas.ts
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug

#1437 Bug 2061335: Remove isAzure check from valuesHaveUpdateFunction
  src/app/home/pages/ClustersPage/components/AddEditClusterModal/AddEditClusterForm.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug

#1436 Bug 2038898: Add valued update check for aws s3/s3 repo type
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/S3Form.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug

#1441 [Backport - 1.7.2] Bug 2038898: Add valued update check for aws s3/s3 repo type (#1436)
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/S3Form.tsx
Labels: bugzilla/severity-low, bugzilla/invalid-bug

#1442 [Backport - 1.7.2] Bug 2061335: Remove isAzure check from valuesHaveUpdateFunction (#1437)
  src/app/home/pages/ClustersPage/components/AddEditClusterModal/AddEditClusterForm.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug

#1445 adding owners files for ci
  OWNERS
Labels: lgtm

#1440 Bug 2058529: fixing state migration table compatibility
  src/app/home/pages/PlansPage/components/AccessLogsModal.tsx
  src/app/home/pages/PlansPage/components/MigrationsTable.tsx
  src/app/home/pages/PlansPage/helpers.ts
  src/app/home/pages/PlansPage/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
  src/app/home/pages/PlansPage/pages/MigrationStepDetailsPage/MigrationStepDetailsPage.tsx
  src/app/plan/duck/selectors.ts
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug, approved

#1446 Cherry-picking: adding owners file and fixing bz 2052589
  OWNERS
  src/app/home/pages/PlansPage/components/AccessLogsModal.tsx
  src/app/home/pages/PlansPage/components/MigrationsTable.tsx
  src/app/home/pages/PlansPage/helpers.ts
  src/app/home/pages/PlansPage/pages/MigrationDetailsPage/MigrationDetailsPage.tsx
  src/app/home/pages/PlansPage/pages/MigrationStepDetailsPage/MigrationStepDetailsPage.tsx
  src/app/plan/duck/selectors.ts
Labels: lgtm

#1444 Bug 2040693: Update repository name validation to use name length validation
  src/app/common/duck/utils.ts
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/AzureForm.tsx
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/GCPForm.tsx
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/S3Form.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug, approved

#1448 [Backport - 1.7.2] Bug 2040695: Fix cluster name validation bug (#1434)
  src/app/common/duck/utils.ts
  src/app/home/pages/ClustersPage/components/AddEditClusterModal/AddEditClusterForm.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug, approved

#1447 Bug 2058172: Add plan status icon update for succeeded rollback
  src/app/home/pages/PlansPage/components/PlanStatusIcon.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug, approved

#1439 Bug 2056962: For non-SCC intra-cluster migrations, don't allow target namespace to equal source namespace
  src/app/home/pages/PlansPage/components/Wizard/WizardFormik.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug, approved

#1449 [Backport - 1.7.2] Bug 2058172: Add plan status icon update for succeeded rollback
  src/app/home/pages/PlansPage/components/PlanStatusIcon.tsx
Labels: bugzilla/severity-low, bugzilla/valid-bug, approved

#1450 [Backport - 1.7.2] Bug 2040693: Update repository name validation to use name length validation
  src/app/common/duck/utils.ts
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/AzureForm.tsx
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/GCPForm.tsx
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/S3Form.tsx
Labels: bugzilla/severity-low, bugzilla/valid-bug, approved

#1452 Bug 2078459: Prevent migStorageRef from being added to plans that don't already have one
  src/client/resources/conversions.ts
Labels: lgtm, bugzilla/valid-bug, approved, bugzilla/severity-medium

#1453 [Backport - 1.7.2] Bug 2078459: Prevent migStorageRef from being added to plans that don't already have one
  src/client/resources/conversions.ts
Labels: bugzilla/valid-bug, approved, bugzilla/severity-medium

#1455 [Backport - 1.7.2] Bug 2038898: Adjust s3 initial values to match expected
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/S3Form.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug, approved

#1454 Bug 2038898: Adjust s3 initial values to match expected
  src/app/home/pages/StoragesPage/components/AddEditStorageModal/ProviderForms/S3Form.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug, approved

#1456 [Backport - 1.7.2] Bug 2056962: For non-SCC intra-cluster migrations, don't allow target namespace to equal source namespace (#1439)
  src/app/home/pages/PlansPage/components/Wizard/WizardFormik.tsx
Labels: lgtm, bugzilla/severity-low, bugzilla/valid-bug, approved

#1457 Bug 2100486: Add conditional for storage error which was preventing submit
  src/app/home/pages/PlansPage/components/Wizard/WizardFormik.tsx
Labels: lgtm, bugzilla/valid-bug, approved, bugzilla/severity-urgent

#1458 [Backport - 1.7.2] Bug 2100486: Add conditional for storage error which was preventing submit @ibolton336
  src/app/home/pages/PlansPage/components/Wizard/WizardFormik.tsx
Labels: lgtm, bugzilla/valid-bug, approved, bugzilla/severity-urgent
